.TH "flickmage.FlickMage" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flickmage.FlickMage
.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstart\fP (Stage stage)  throws Exception "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main application class\&.
.PP
\fBAuthor:\fP
.RS 4
Seitan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void flickmage\&.FlickMage\&.main (String [] args)\fC [static]\fP"

.SS "void flickmage\&.FlickMage\&.start (Stage stage) throws Exception"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
