.TH "flickmage.FXMLDocumentController" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flickmage.FXMLDocumentController
.SH SYNOPSIS
.br
.PP
.PP
Inherits Initializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP (URL url, ResourceBundle rb)"
.br
.ti -1c
.RI "void \fBSetDownloadStatusDone\fP (int done)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Pane \fBImageContainerPane\fP"
.br
.ti -1c
.RI "Button \fBSearchByTagButton\fP"
.br
.ti -1c
.RI "TextField \fBTagTextField\fP"
.br
.ti -1c
.RI "Circle \fBLoadingCircle\fP"
.br
.ti -1c
.RI "TextArea \fBDetailsTextArea\fP"
.br
.ti -1c
.RI "ImageView \fBLogoImage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main class controller for UI items
.PP
\fBAuthor:\fP
.RS 4
Seitan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void flickmage\&.FXMLDocumentController\&.initialize (URL url, ResourceBundle rb)"

.SS "void flickmage\&.FXMLDocumentController\&.SetDownloadStatusDone (int done)"

.SH "Member Data Documentation"
.PP 
.SS "TextArea flickmage\&.FXMLDocumentController\&.DetailsTextArea"

.SS "Pane flickmage\&.FXMLDocumentController\&.ImageContainerPane"

.SS "Circle flickmage\&.FXMLDocumentController\&.LoadingCircle"

.SS "ImageView flickmage\&.FXMLDocumentController\&.LogoImage"

.SS "Button flickmage\&.FXMLDocumentController\&.SearchByTagButton"

.SS "TextField flickmage\&.FXMLDocumentController\&.TagTextField"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
