.TH "networking.FileManager" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
networking.FileManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBfillData\fP (String id, \fBImageViewWrapper\fP viewWrapper)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFileManager\fP - class used for parsing XML into DOM and DOM structures into XML files\&.
.PP
\fBAuthor:\fP
.RS 4
Seitan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void networking\&.FileManager\&.fillData (String id, \fBImageViewWrapper\fP viewWrapper)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
