.TH "networking.Network" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
networking.Network
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBsendHTTPGet\fP (String usedURL)  throws IOException "
.br
.ti -1c
.RI "static void \fBdownloadImage\fP (String url, String fileName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBNetwork\fP class used to send http requests and downloading image from URL\&.
.PP
\fBAuthor:\fP
.RS 4
Seitan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void networking\&.Network\&.downloadImage (String url, String fileName)\fC [static]\fP"

.SS "static String networking\&.Network\&.sendHTTPGet (String usedURL) throws IOException\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
