.TH "networking.ThreadManager" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
networking.ThreadManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBexecuteWorkWithTag\fP (String tag)"
.br
.ti -1c
.RI "static void \fBexecuteWork\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBThreadManager\fP - I added this class to have another layer between users of worker thread and the worker thread
.PP
\fBAuthor:\fP
.RS 4
Seitan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void networking\&.ThreadManager\&.executeWork ()\fC [static]\fP"

.SS "static void networking\&.ThreadManager\&.executeWorkWithTag (String tag)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
