.TH "E:/Git/flickmage/flickmage/src/utils/OSSpecific.java" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Git/flickmage/flickmage/src/utils/OSSpecific.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fButils\&.OSSpecific\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fButils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
