.TH "ui.ImageViewWrapper" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui.ImageViewWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBgetID\fP ()"
.br
.ti -1c
.RI "void \fBsetURL\fP (String u)"
.br
.ti -1c
.RI "String \fBgetURL\fP ()"
.br
.ti -1c
.RI "void \fBsetTitle\fP (String t)"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "void \fBsetTakenDateFromString\fP (String d)"
.br
.ti -1c
.RI "Date \fBgetTakenDate\fP ()"
.br
.ti -1c
.RI "String \fBgetTakenDateAsString\fP ()"
.br
.ti -1c
.RI "Date \fBgetPublishDate\fP ()"
.br
.ti -1c
.RI "String \fBgetPublishDateAsString\fP ()"
.br
.ti -1c
.RI "void \fBsetPublishDateFromString\fP (String d)"
.br
.ti -1c
.RI "void \fBsetSelected\fP ()"
.br
.ti -1c
.RI "void \fBsetUnselected\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBImageViewWrapper\fP - Data structure used to store info about Flickr posts: URL, metadata, etc
.PP
\fBAuthor:\fP
.RS 4
Seitan 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String ui\&.ImageViewWrapper\&.getID ()"

.SS "Date ui\&.ImageViewWrapper\&.getPublishDate ()"

.SS "String ui\&.ImageViewWrapper\&.getPublishDateAsString ()"

.SS "Date ui\&.ImageViewWrapper\&.getTakenDate ()"

.SS "String ui\&.ImageViewWrapper\&.getTakenDateAsString ()"

.SS "String ui\&.ImageViewWrapper\&.getTitle ()"

.SS "String ui\&.ImageViewWrapper\&.getURL ()"

.SS "void ui\&.ImageViewWrapper\&.setPublishDateFromString (String d)"

.SS "void ui\&.ImageViewWrapper\&.setSelected ()"

.SS "void ui\&.ImageViewWrapper\&.setTakenDateFromString (String d)"

.SS "void ui\&.ImageViewWrapper\&.setTitle (String t)"

.SS "void ui\&.ImageViewWrapper\&.setUnselected ()"

.SS "void ui\&.ImageViewWrapper\&.setURL (String u)"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
