.TH "ui.UIManager" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui.UIManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitializeController\fP (\fBFXMLDocumentController\fP c)"
.br
.ti -1c
.RI "void \fBdownloadDone\fP (Vector< String > ids)"
.br
.ti -1c
.RI "void \fBstartDownloadByTag\fP (String tag)"
.br
.ti -1c
.RI "void \fBstartDownload\fP ()"
.br
.ti -1c
.RI "void \fBimageSelected\fP (\fBImageViewWrapper\fP wr)"
.br
.ti -1c
.RI "void \fBsortByDateTaken\fP (Boolean b)"
.br
.ti -1c
.RI "void \fBSaveFileToSystemGallery\fP ()"
.br
.ti -1c
.RI "void \fBOpenFileInBrowser\fP ()"
.br
.ti -1c
.RI "void \fBShareFileViaMail\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBUIManager\fP \fBgetInstance\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUIManager\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUIManager\fP - big class used to updated UI logic and to manage connection to worker thread\&.
.PP
\fBAuthor:\fP
.RS 4
Seitan 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ui\&.UIManager\&.UIManager ()\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ui\&.UIManager\&.downloadDone (Vector< String > ids)"

.SS "static \fBUIManager\fP ui\&.UIManager\&.getInstance ()\fC [static]\fP"

.SS "void ui\&.UIManager\&.imageSelected (\fBImageViewWrapper\fP wr)"

.SS "void ui\&.UIManager\&.initializeController (\fBFXMLDocumentController\fP c)"

.SS "void ui\&.UIManager\&.OpenFileInBrowser ()"

.SS "void ui\&.UIManager\&.SaveFileToSystemGallery ()"

.SS "void ui\&.UIManager\&.ShareFileViaMail ()"

.SS "void ui\&.UIManager\&.sortByDateTaken (Boolean b)"

.SS "void ui\&.UIManager\&.startDownload ()"

.SS "void ui\&.UIManager\&.startDownloadByTag (String tag)"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
