.TH "utils.CustomLogger" 3 "Thu Feb 16 2017" "FlickMage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.CustomLogger
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Logger \fBlogger\fP = Logger\&.getLogger( CustomLogger\&.class\&.getName() )"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Logger utils\&.CustomLogger\&.logger = Logger\&.getLogger( CustomLogger\&.class\&.getName() )\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for FlickMage from the source code\&.
